name: url_web
description: "A simple url shortner"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: 3.6.0
  flutter: 3.27.1

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  intl: ^0.20.2
  lottie: ^3.3.1
  provider: ^6.1.2
  pwa_install: ^0.0.6
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/logo/
